### ISSUE TITLE
No source code only exe files

### ISSUE THREAD

**Issue by zsiki** [zeuszultra/zeusz_ultra#1]
It is not common to store binary exe files in a github  repo of an open source program. I cannot find the source code, please add your source code and the necessary make files to build binary executables or add your binary executables to a release.

**Comment by zeuszultra** [comment]
This repository is meant also for people without special technical skills, so that they can try out everything right away.
Source codes of core technologies presented in this repository can be found here: https://github.com/fkhydra?tab=repositories
I am planning to provide concrete source codes here as well however, but it has low prio at the moment.

**Comment by zsiki** [comment]
I think you mixed up the function of sourceforge (or similar) and github.
